try {
        let a = 0;
        console( program )
        console.log( "Program can Sucessfully" );
} catch {
        console.log( "This is an error " );
        console.log(p);
}



finally {
console.log( "Hello This is an Error" );
}